PACKAGE_NAME="greenboost"
PACKAGE_VERSION="@PKGVER@"
BUILT_MODULE_NAME[0]="greenboost"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CC=clang LLVM=1 modules"
